// <auto-generated />
using System;
using Hba.Dispatch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hba.Dispatch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DispatchDbContext))]
    [Migration("20260927081734_PersonalDataReads")]
    partial class PersonalDataReads
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dispatch")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hba.BuildingBlocks.Messaging.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("EventId");

                    b.ToTable("inbox_messages", "dispatch");
                });

            modelBuilder.Entity("Hba.BuildingBlocks.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt", "NextAttemptAt")
                        .HasFilter("\"PublishedAt\" IS NULL");

                    b.ToTable("outbox_messages", "dispatch");
                });

            modelBuilder.Entity("Hba.BuildingBlocks.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Scope", "Key");

                    b.ToTable("idempotency_records", "dispatch");
                });

            modelBuilder.Entity("Hba.BuildingBlocks.Persistence.PersonalDataRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReaderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReaderRoles")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ReaderId", "ReadAt");

                    b.HasIndex("SubjectId", "ReadAt");

                    b.ToTable("personal_data_reads", "dispatch");
                });

            modelBuilder.Entity("Hba.Dispatch.Domain.Dispatching.DispatchAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedDriverId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("assigned_driver_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentWave")
                        .HasColumnType("integer")
                        .HasColumnName("current_wave");

                    b.Property<DateTimeOffset?>("CurrentWaveOpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_wave_opened_at");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<long>("DriverEarningXof")
                        .HasColumnType("bigint")
                        .HasColumnName("driver_earning_xof");

                    b.Property<string>("PickupLandmark")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pickup_landmark");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TripDistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("trip_distance_meters");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeliveryId")
                        .IsUnique();

                    b.HasIndex("Status", "CurrentWaveOpenedAt");

                    b.ToTable("dispatches", "dispatch");
                });

            modelBuilder.Entity("Hba.Dispatch.Domain.Dispatching.DispatchAggregate", b =>
                {
                    b.OwnsOne("Hba.Dispatch.Domain.ValueObjects.GeoPoint", "Pickup", b1 =>
                        {
                            b1.Property<Guid>("DispatchAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("pickup_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("pickup_longitude");

                            b1.HasKey("DispatchAggregateId");

                            b1.ToTable("dispatches", "dispatch");

                            b1.WithOwner()
                                .HasForeignKey("DispatchAggregateId");
                        });

                    b.OwnsMany("Hba.Dispatch.Domain.Dispatching.Offer", "Offers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("DeclineReason")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("decline_reason");

                            b1.Property<int>("DistanceToPickupMeters")
                                .HasColumnType("integer")
                                .HasColumnName("distance_to_pickup_meters");

                            b1.Property<string>("DriverId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("driver_id");

                            b1.Property<DateTimeOffset>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("expires_at");

                            b1.Property<DateTimeOffset?>("ResolvedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("resolved_at");

                            b1.Property<DateTimeOffset>("SentAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("sent_at");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.Property<int>("WaveNumber")
                                .HasColumnType("integer")
                                .HasColumnName("wave_number");

                            b1.Property<Guid>("dispatch_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("SentAt");

                            b1.HasIndex("dispatch_id");

                            b1.HasIndex("DriverId", "Status");

                            b1.HasIndex("Status", "ExpiresAt");

                            b1.ToTable("offers", "dispatch");

                            b1.WithOwner()
                                .HasForeignKey("dispatch_id");
                        });

                    b.Navigation("Offers");

                    b.Navigation("Pickup")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
