// <auto-generated />
using System;
using Hba.Delivery.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hba.Delivery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    partial class DeliveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("delivery")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hba.BuildingBlocks.Messaging.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("EventId");

                    b.ToTable("inbox_messages", "delivery");
                });

            modelBuilder.Entity("Hba.BuildingBlocks.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt", "NextAttemptAt")
                        .HasFilter("\"PublishedAt\" IS NULL");

                    b.ToTable("outbox_messages", "delivery");
                });

            modelBuilder.Entity("Hba.BuildingBlocks.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Scope", "Key");

                    b.ToTable("idempotency_records", "delivery");
                });

            modelBuilder.Entity("Hba.Delivery.Domain.Deliveries.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArrivedAtPickupAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentOfferId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DeliveryProofObjectKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MerchantId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PackageDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PackageWeightGrams")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PickupPointId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PickupProofObjectKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "CreatedAt");

                    b.HasIndex("MerchantId", "CreatedAt");

                    b.HasIndex("PartnerId", "ExternalOrderId")
                        .IsUnique()
                        .HasFilter("\"ExternalOrderId\" IS NOT NULL");

                    b.ToTable("deliveries", "delivery");
                });

            modelBuilder.Entity("Hba.Delivery.Domain.Deliveries.Delivery", b =>
                {
                    b.OwnsOne("Hba.Delivery.Domain.Deliveries.AssignedDriver", "Driver", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("driver_name");

                            b1.Property<string>("DriverId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("driver_id");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("driver_phone");

                            b1.Property<string>("VehiclePlate")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("driver_vehicle_plate");

                            b1.Property<int>("VehicleType")
                                .HasColumnType("integer")
                                .HasColumnName("driver_vehicle_type");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("deliveries", "delivery");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");
                        });

                    b.OwnsOne("Hba.Delivery.Domain.ValueObjects.Location", "Dropoff", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContactName")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("dropoff_contact_name");

                            b1.Property<string>("Landmark")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("dropoff_landmark");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("dropoff_notes");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("dropoff_phone");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("deliveries", "delivery");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");

                            b1.OwnsOne("Hba.Delivery.Domain.ValueObjects.GeoPoint", "Point", b2 =>
                                {
                                    b2.Property<Guid>("LocationDeliveryId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("dropoff_latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("dropoff_longitude");

                                    b2.HasKey("LocationDeliveryId");

                                    b2.ToTable("deliveries", "delivery");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationDeliveryId");
                                });

                            b1.Navigation("Point")
                                .IsRequired();
                        });

                    b.OwnsOne("Hba.Delivery.Domain.ValueObjects.Location", "Pickup", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContactName")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("pickup_contact_name");

                            b1.Property<string>("Landmark")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("pickup_landmark");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("pickup_notes");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("pickup_phone");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("deliveries", "delivery");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");

                            b1.OwnsOne("Hba.Delivery.Domain.ValueObjects.GeoPoint", "Point", b2 =>
                                {
                                    b2.Property<Guid>("LocationDeliveryId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("pickup_latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("pickup_longitude");

                                    b2.HasKey("LocationDeliveryId");

                                    b2.ToTable("deliveries", "delivery");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationDeliveryId");
                                });

                            b1.Navigation("Point")
                                .IsRequired();
                        });

                    b.OwnsOne("Hba.Delivery.Domain.Deliveries.Recipient", "Recipient", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("recipient_name");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("recipient_phone");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("deliveries", "delivery");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");
                        });

                    b.OwnsOne("Hba.Delivery.Domain.ValueObjects.DeliveryOtp", "Otp", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("otp_code");

                            b1.Property<int>("FailedAttempts")
                                .HasColumnType("integer")
                                .HasColumnName("otp_failed_attempts");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("deliveries", "delivery");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");
                        });

                    b.OwnsOne("Hba.Delivery.Domain.ValueObjects.PricingSnapshot", "Pricing", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DistanceMeters")
                                .HasColumnType("integer")
                                .HasColumnName("distance_meters");

                            b1.Property<int>("DurationSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("duration_seconds");

                            b1.Property<string>("QuoteId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("quote_id");

                            b1.Property<DateTimeOffset>("QuotedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("quoted_at");

                            b1.Property<string>("TariffVersion")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("tariff_version");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("deliveries", "delivery");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");

                            b1.OwnsOne("Hba.Delivery.Domain.ValueObjects.MoneyXof", "BaseFare", b2 =>
                                {
                                    b2.Property<Guid>("PricingSnapshotDeliveryId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint")
                                        .HasColumnName("price_base_xof");

                                    b2.HasKey("PricingSnapshotDeliveryId");

                                    b2.ToTable("deliveries", "delivery");

                                    b2.WithOwner()
                                        .HasForeignKey("PricingSnapshotDeliveryId");
                                });

                            b1.OwnsOne("Hba.Delivery.Domain.ValueObjects.MoneyXof", "DistanceFare", b2 =>
                                {
                                    b2.Property<Guid>("PricingSnapshotDeliveryId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint")
                                        .HasColumnName("price_distance_xof");

                                    b2.HasKey("PricingSnapshotDeliveryId");

                                    b2.ToTable("deliveries", "delivery");

                                    b2.WithOwner()
                                        .HasForeignKey("PricingSnapshotDeliveryId");
                                });

                            b1.OwnsOne("Hba.Delivery.Domain.ValueObjects.MoneyXof", "DriverEarning", b2 =>
                                {
                                    b2.Property<Guid>("PricingSnapshotDeliveryId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint")
                                        .HasColumnName("driver_earning_xof");

                                    b2.HasKey("PricingSnapshotDeliveryId");

                                    b2.ToTable("deliveries", "delivery");

                                    b2.WithOwner()
                                        .HasForeignKey("PricingSnapshotDeliveryId");
                                });

                            b1.OwnsOne("Hba.Delivery.Domain.ValueObjects.MoneyXof", "SurgeFare", b2 =>
                                {
                                    b2.Property<Guid>("PricingSnapshotDeliveryId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint")
                                        .HasColumnName("price_surge_xof");

                                    b2.HasKey("PricingSnapshotDeliveryId");

                                    b2.ToTable("deliveries", "delivery");

                                    b2.WithOwner()
                                        .HasForeignKey("PricingSnapshotDeliveryId");
                                });

                            b1.OwnsOne("Hba.Delivery.Domain.ValueObjects.MoneyXof", "Total", b2 =>
                                {
                                    b2.Property<Guid>("PricingSnapshotDeliveryId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint")
                                        .HasColumnName("price_total_xof");

                                    b2.HasKey("PricingSnapshotDeliveryId");

                                    b2.ToTable("deliveries", "delivery");

                                    b2.WithOwner()
                                        .HasForeignKey("PricingSnapshotDeliveryId");
                                });

                            b1.Navigation("BaseFare")
                                .IsRequired();

                            b1.Navigation("DistanceFare")
                                .IsRequired();

                            b1.Navigation("DriverEarning")
                                .IsRequired();

                            b1.Navigation("SurgeFare")
                                .IsRequired();

                            b1.Navigation("Total")
                                .IsRequired();
                        });

                    b.Navigation("Driver");

                    b.Navigation("Dropoff")
                        .IsRequired();

                    b.Navigation("Otp")
                        .IsRequired();

                    b.Navigation("Pickup")
                        .IsRequired();

                    b.Navigation("Pricing")
                        .IsRequired();

                    b.Navigation("Recipient")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
