// <auto-generated />
using System;
using Hba.Directory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hba.Directory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DirectoryDbContext))]
    [Migration("20260921225031_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("directory")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hba.BuildingBlocks.Messaging.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("EventId");

                    b.ToTable("inbox_messages", "directory");
                });

            modelBuilder.Entity("Hba.BuildingBlocks.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt", "NextAttemptAt")
                        .HasFilter("\"PublishedAt\" IS NULL");

                    b.ToTable("outbox_messages", "directory");
                });

            modelBuilder.Entity("Hba.BuildingBlocks.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Scope", "Key");

                    b.ToTable("idempotency_records", "directory");
                });

            modelBuilder.Entity("Hba.Directory.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("customers", "directory");
                });

            modelBuilder.Entity("Hba.Directory.Domain.Merchants.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AveragePreparationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("average_preparation_minutes");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deactivation_reason");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("LegalName");

                    b.ToTable("merchants", "directory");
                });

            modelBuilder.Entity("Hba.Directory.Domain.Customers.Customer", b =>
                {
                    b.OwnsMany("Hba.Directory.Domain.Customers.FavoriteAddress", "FavoriteAddresses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean")
                                .HasColumnName("is_default");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("label");

                            b1.HasKey("Id");

                            b1.HasIndex("CustomerId");

                            b1.ToTable("customer_favorite_addresses", "directory");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.OwnsOne("Hba.Directory.Domain.ValueObjects.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("FavoriteAddressId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("ContactName")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("character varying(120)")
                                        .HasColumnName("contact_name");

                                    b2.Property<string>("Landmark")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("landmark");

                                    b2.Property<string>("Notes")
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("notes");

                                    b2.Property<string>("Phone")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("phone");

                                    b2.HasKey("FavoriteAddressId");

                                    b2.ToTable("customer_favorite_addresses", "directory");

                                    b2.WithOwner()
                                        .HasForeignKey("FavoriteAddressId");

                                    b2.OwnsOne("Hba.Directory.Domain.ValueObjects.GeoPoint", "Point", b3 =>
                                        {
                                            b3.Property<Guid>("AddressFavoriteAddressId")
                                                .HasColumnType("uuid");

                                            b3.Property<double>("Latitude")
                                                .HasColumnType("double precision")
                                                .HasColumnName("latitude");

                                            b3.Property<double>("Longitude")
                                                .HasColumnType("double precision")
                                                .HasColumnName("longitude");

                                            b3.HasKey("AddressFavoriteAddressId");

                                            b3.ToTable("customer_favorite_addresses", "directory");

                                            b3.WithOwner()
                                                .HasForeignKey("AddressFavoriteAddressId");
                                        });

                                    b2.Navigation("Point")
                                        .IsRequired();
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.Navigation("FavoriteAddresses");
                });

            modelBuilder.Entity("Hba.Directory.Domain.Merchants.Merchant", b =>
                {
                    b.OwnsMany("Hba.Directory.Domain.Merchants.PickupPoint", "PickupPoints", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("is_active");

                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.Property<string>("OpeningHoursRaw")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("opening_hours");

                            b1.HasKey("Id");

                            b1.HasIndex("MerchantId");

                            b1.ToTable("merchant_pickup_points", "directory");

                            b1.WithOwner()
                                .HasForeignKey("MerchantId");

                            b1.OwnsOne("Hba.Directory.Domain.ValueObjects.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("PickupPointId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("ContactName")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("character varying(120)")
                                        .HasColumnName("contact_name");

                                    b2.Property<string>("Landmark")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("landmark");

                                    b2.Property<string>("Notes")
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("notes");

                                    b2.Property<string>("Phone")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("phone");

                                    b2.HasKey("PickupPointId");

                                    b2.ToTable("merchant_pickup_points", "directory");

                                    b2.WithOwner()
                                        .HasForeignKey("PickupPointId");

                                    b2.OwnsOne("Hba.Directory.Domain.ValueObjects.GeoPoint", "Point", b3 =>
                                        {
                                            b3.Property<Guid>("AddressPickupPointId")
                                                .HasColumnType("uuid");

                                            b3.Property<double>("Latitude")
                                                .HasColumnType("double precision")
                                                .HasColumnName("latitude");

                                            b3.Property<double>("Longitude")
                                                .HasColumnType("double precision")
                                                .HasColumnName("longitude");

                                            b3.HasKey("AddressPickupPointId");

                                            b3.ToTable("merchant_pickup_points", "directory");

                                            b3.WithOwner()
                                                .HasForeignKey("AddressPickupPointId");
                                        });

                                    b2.Navigation("Point")
                                        .IsRequired();
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.Navigation("PickupPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
